# Generated by Django 4.0.1 on 2022-02-07 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='nome',
            new_name='nome_completo',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sobrenome',
        ),
    ]
