# Generated by Django 4.0.1 on 2022-02-07 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_nome_customuser_nome_completo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nome_completo',
            field=models.CharField(max_length=150, verbose_name='nome completo'),
        ),
    ]
