# Generated by Django 4.0.1 on 2022-02-12 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_customuser_is_active_alter_customuser_is_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendamento', models.DateField(verbose_name='Data do Agendamento')),
            ],
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_estabelecimento', models.CharField(max_length=70, verbose_name='Nome do Estabelecimento')),
                ('codigo_cnes', models.CharField(max_length=30, verbose_name='Código CNES')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento_Cidadao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Agendamento Marcado')),
                ('hora_agendamento', models.TimeField(verbose_name='Hora do Agendamento')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.agendamento')),
                ('cidadao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='agendamento',
            name='id_estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estabelecimento'),
        ),
    ]
