# Generated by Django 4.0.1 on 2022-02-12 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_agendamento_estabelecimento_agendamento_cidadao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='id_estabelecimento',
            new_name='estabelecimento',
        ),
    ]
