# Generated by Django 4.0.1 on 2022-02-14 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_agendamento_estabelecimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estabelecimento', verbose_name='Estabelecimento'),
        ),
        migrations.AlterField(
            model_name='agendamento_cidadao',
            name='agendamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.agendamento', verbose_name='Agendamento'),
        ),
        migrations.AlterField(
            model_name='agendamento_cidadao',
            name='cidadao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='agendamento_cidadao',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Agendamento Ativo'),
        ),
    ]
