# Generated by Django 4.1.7 on 2023-03-29 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_agendamento_estabelecimento_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agendamento_Cidadao',
            new_name='AgendamentoCidadao',
        ),
    ]
